spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#TODO: implements integration tests with feign
feign-client:
  market-data:
    name: market-data
    url: localhost

app-context:
  scheduler:
    disabled: true