spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#TODO: implements integration tests with feign
feign-client:
  investment-calculator:
    name: investment-calculator
    url: http://localhost:8081/api
  market-data:
    name: market-data
    url: localhost

app-context:
  scheduler:
    disabled: true
  aws:
    disabled: true