server:
  servlet:
    contextPath: /api

aws:
  accessKey: ${AWS_ACCESS_KEY:}
  secretKey: ${AWS_SECRET_KEY:}
  region: ${AWS_REGION:us-east-1}

spring:
  flyway:
      enabled: false
  datasource:
    url: ${datasource.url}
    username: ${datasource.user}
    password: ${datasource.password}
  ## TODO: Create a Hikari configuration
  ## TODO: Read about spring.jpa.open-in-view
  jpa:
    hibernate:
      ddl-auto: none
feign:
  client:
    config:
      market-data:
        defaultRequestHeaders:
          Authorization: Bearer ${feign-client.market-data.token}

app-context:
  scheduler:
    disabled: false
  aws:
    disabled: false