server:
  port: ${PORT}
aws:
  sqs:
    execution-event-changed-queue: https://sqs.us-east-1.amazonaws.com/446633124077/execution-event-changed
    execution-pnl-open-changed-queue: https://sqs.us-east-1.amazonaws.com/446633124077/execution-pnl-open-event-changed

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


datasource:
  url: ${JDBC_DATABASE_URL}
  user: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}


feign-client:
  investment-calculator:
    name: investment-calculator
    url: ${INVESTMENT_CALCULATOR_URL}
  market-data:
    token: ${MARKET_DATA_TOKEN}
    url: https://api.dadosdemercado.com.br/v1/
    name: market-data