spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


datasource:
  url: jdbc:postgresql://localhost:5432/investment-management
  user: developer
  password: 123456
