version: '3.1'

services:
  db:
    container_name: 'postgres-investment-management'
    image: postgres:15
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: investment-management
    ports:
      - "5432:5432"
    network_mode: 'host'