version: '3.1'

services:
  db:
    container_name: 'postgres-investment-management'
    image: postgres:15
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: investment-management
    ports:
      - "5432:5432"
    network_mode: 'host'
  in-memory-db:
    container_name: 'redis-investment-management'
    image: redis:7.0.8
    ports:
      - "6379:6379"
    network_mode: 'host'
  redis-insight:
    container_name: 'redis-insight'
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
      - "6379:6379"
    network_mode: 'host'
