CREATE OR REPLACE VIEW EXECUTIONS_QUANTITY_TOTALIZER AS SELECT  * FROM (
	SELECT
	    ID,
	    I_ORIGINS,
	    I_STOCKS,
	    I_WALLETS,
	    PROFIT_PERCENTAGE,
	    (EXECUTIONS.EXECUTED_QUANTITY - ((SELECT COALESCE(SUM(SOLD_EXECUTIONS.EXECUTED_QUANTITY),0)  FROM EXECUTIONS SOLD_EXECUTIONS WHERE SOLD_EXECUTIONS.I_ORIGINS = EXECUTIONS.ID))) AS EXECUTED_QUANTITY,
	    EXECUTED_PRICE, EXECUTED_VOLUME,
	    STATUS,
	    EXECUTED_AT,
	    CREATED_AT,
	    UPDATED_AT, 
	    PNL_OPEN,
	    PNL_CLOSE
	    FROM EXECUTIONS WHERE EXECUTIONS.STATUS = '0'
	UNION ALL
	SELECT * FROM EXECUTIONS WHERE STATUS = '1'
) AS TAB;