version: '3.1'

# Ver sobre volumes para adicionar os beats para métricas
services:
  kibana:
    container_name: 'kibana'
    image: kibana:8.5.3
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    networks:
      - monitoring
    depends_on:
      - elastic
  elastic:
    networks:
      - monitoring
    container_name: 'elasticsearch'
    image: elasticsearch:8.5.3
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"

networks:
  monitoring:
    driver: 'bridge'